# Copyright (C) 2016 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

##include $(TOPDIR)/rules.mk

##LUCI_TITLE:=LuCI support for KSpeeder
##LUCI_DEPENDS:=+istoreenhance
##LUCI_PKGARCH:=all
##PKG_VERSION:=0.2.1-1
# PKG_RELEASE MUST be empty for luci.mk
##PKG_RELEASE:=

##include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
#------以上原始makefile，恢复时，“#”不用改，取消“##”即可----#

#-----------以下修改后的makefile（版本号规则）------------#

# Copyright (C) 2016 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for KSpeeder
LUCI_DEPENDS:=+istoreenhance
LUCI_PKGARCH:=all
PKG_VERSION:=0.2.1
# PKG_RELEASE MUST be empty for luci.mk
PKG_RELEASE:=

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

